<손수원> pull request
LionHyerin/NEXT_GitCollaboration pull request #34
Opened 2022-05-14 06:44 UTC by sonsoowon

안녕하세요

2022-05-14 06:45 UTC, extrajunwan commented on practice.html
> +    <p>춘자 떡꼬치</p>
근본 맛집 춘자!

2022-05-14 06:46 UTC, Moi1oM requested changes
춘자는짱이다

2022-05-14 06:46 UTC, Moi1oM commented on practice.html
> +    <p>춘자 떡꼬치</p>
춘자춘자!

2022-05-18 09:50 UTC, Park747 commented on practice.html
> +    <p>춘자 떡꼬치</p>
춘자

2022-07-07 07:24 UTC, closed without merging